


### Register a new user
POST http://localhost:8000/api/register
Accept: application/json
Content-Type: application/json

{
  "name": "Aouad mohammed",
  "email": "ufeufuwe@example.com",
  "password": "password123",
  "password_confirmation": "password123",
  "role": "admin"
}


### Login a user
POST http://localhost:8000/api/login
Accept: application/json
Content-Type: application/json

{
  "email": "ufeufuwe@example.com",
  "password": "password123"
}


### Logout the user (requires authentication)
POST http://localhost:8000/api/logout
Accept: application/json
Authorization: Bearer 3|GY44DuE2vJ9GrmadDMHNHjPvUkGfm3WmZEsK63kU4a034726


### Contact
POST http://localhost:8000/api/contact
Accept: application/json
Content-Type: application/json

{
  "name": "Aouad Mohammed",
  "email": "aouad6@gmail.com",
  "phone": "0689104243",
  "message": "test tsest"
}


### Create time slot
POST http://localhost:8000/api/times
Authorization: Bearer 31|5T4XkPjK3xeKBxzV7l7YaUyBvSloqCOMeGHND5dW83a3d48d
Content-Type: application/json
Accept: application/json

{
  "date": "2025-05-01",
  "time": "10:00"
}