## get all time slots
GET http://localhost:8000/api/times?date=2025-05-01
Authorization: Bearer 8|R4JsiaAU7qTknHPzf9rHmRbYFCd9na3W7Oj9XvWmb8fcf007
Content-Type: application/json
Accept: application/json


### Register a new user
POST http://localhost:8000/api/register
Accept: application/json
Content-Type: application/json

{
  "name": "Aouad mohammed",
  "email": "3@example.com",
  "password": "password123",
  "password_confirmation": "password123",
  "role": "admin"
}


### Login a user
POST http://localhost:8000/api/login
Accept: application/json
Content-Type: application/json

{
  "email": "3@example.com",
  "password": "password123"
}


### Logout the user (requires authentication)
POST http://localhost:8000/api/logout
Accept: application/json
Authorization: Bearer 2|xwNQSSG5PZIMTzhvb166nXKupwyvDZlZhQD6jGmR801229dd


### Contact
POST http://localhost:8000/api/contact
Accept: application/json
Content-Type: application/json

{
  "name": "Aouad Mohammed",
  "email": "aouad6@gmail.com",
  "phone": "0689104243",
  "message": "test tsest"
}


### Create time slot
POST http://localhost:8000/api/times
Authorization: Bearer 8|R4JsiaAU7qTknHPzf9rHmRbYFCd9na3W7Oj9XvWmb8fcf007
Content-Type: application/json
Accept: application/json

{
  "date": "2025-05-01",
  "time": "15:00"
}


###
GET http://localhost:8000/api/appointments
Authorization: Bearer 8|R4JsiaAU7qTknHPzf9rHmRbYFCd9na3W7Oj9XvWmb8fcf007
Accept: application/json
Accept: application/json


### book an appoi
POST http://localhost:8000/api/appointments
Content-Type: application/json
Authorization: Bearer 9|U6byVtA4Mx36m10MF7bQ3OJ6uNj14LgeDpErNetZd2bee411
Accept: application/json

{
  "time_slot_id": 2
}


###
PUT http://localhost:8000/api/appointments/1
Content-Type: application/json
Authorization: Bearer 10|Mgbva9DBh5ggdaSd0ldYOmT5moP3BVrseQJGniXc10a25fcb
Accept: application/json

{
  "status": "accepted"
}


###
DELETE http://localhost:8000/api/appointments/2
Authorization: Bearer 10|Mgbva9DBh5ggdaSd0ldYOmT5moP3BVrseQJGniXc10a25fcb
Accept: application/json
Content-Type: application/json