name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_DATABASE: laravel
          MYSQL_USER: laravel
          MYSQL_PASSWORD: password
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, bcmath, pdo, pdo_mysql

    - name: Install Composer dependencies
      working-directory: ./Back-End
      run: composer install --no-interaction --prefer-dist

    - name: Setup Laravel environment
      working-directory: ./Back-End
      run: |
        cp .env.example .env
        php artisan key:generate
        echo "DB_CONNECTION=mysql" >> .env
        echo "DB_HOST=127.0.0.1" >> .env
        echo "DB_PORT=3306" >> .env
        echo "DB_DATABASE=laravel" >> .env
        echo "DB_USERNAME=laravel" >> .env
        echo "DB_PASSWORD=password" >> .env

    - name: Run migrations
      working-directory: ./Back-End
      run: php artisan migrate --force

    - name: Run Laravel tests
      working-directory: ./Back-End
      run: php artisan test

  react-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install frontend dependencies
      working-directory: ./FRENT_END/Dentist_frentEnd
      run: npm install

    - name: Run React tests
      working-directory: ./FRENT_END/Dentist_frentEnd
      run: npm test -- --watchAll=false
